<html>
<head>
<title><%Title%></title>
<meta http-equiv="Content-Type" content="text/html; charset=<%charset%>">
<%RefreshMeta%>
<link rel="stylesheet" type="text/css" href="<%CSS%>">
<%JavaScripts%>
</head>
<body bgcolor="<%BODYBG%>" topmargin="0" leftmargin="0" marginheight="0" marginwidth="0">

<table width="100%" border=0 cellpadding=0 cellspacing=0>
  <tr>
    <td colspan="3" bgcolor="#226474"><img src="/images/ClassicUT/1-1.gif" width=26 height=6 hspace=0 vspace=0 border=0 align="left"><img src="/images/ClassicUT/1-2.gif" width=114 height=6 hspace=0 vspace=0 border=0 align="right"></td>
  </tr>
  <tr>
    <td width="21" bgcolor="Black"><img src="/images/ClassicUT/2-1.gif" width=21 height=19 hspace=0 vspace=0 border=0 align="left"></td>
    <td width="100%" align="LEFT" bgcolor="Black"><font face="Verdana,Arial" color="White" size="-1"><b><%Section%></b></font><br></td>
    <td width="114" align="RIGHT" bgcolor="Black"><img src="/images/ClassicUT/2-2.gif" width=114 height=19 hspace=0 vspace=0 border=0 align="right"></td>
  </tr>
  <tr>
    <td bgcolor="#226474" colspan="3"><img src="/images/ClassicUT/3-1.gif" width=26 height=7 hspace=0 vspace=0 border=0 align="left"><img src="/images/ClassicUT/3-2.gif" width=114 height=7 hspace=0 vspace=0 border=0 align="right"></td>
  </tr>
</table>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="26" align="RIGHT" bgcolor="Black"><img vspace="0" hspace="0" src="/images/ClassicUT/4-2.gif" width=26 height=26 align="right"></td>
    <td align="LEFT" bgcolor="Black" width="100%"><font face="Verdana,Arial" color="33cc66"><b><%SubTitle%></b></font></td>
	<td width="67" align="LEFT"><img vspace="0" hspace="0" src="/images/ClassicUT/4-1.gif" width=67 height=26 align="left"></td>
	<td width="1" align="RIGHT" valign=middle><font face="Verdana,Arial" size="-1" color=white><b>«</b><a href="mailto:<%BugAddress%>">Bugs?</a><b>»</b></font></td>
	<td width="26" align="RIGHT"><img vspace="0" hspace="0" src="/images/ClassicUT/4-2.gif" width=26 height=26 align="right"></td>
  </tr>
</table>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td rowspan="2" colspan="2"><img vspace="0" hspace="0" src="/images/ClassicUT/5-1.gif" width=24 height=21 align="left"></td>
	<td width="100%" height="9" bgcolor="#226474"><img vspace="0" hspace="0" src="/images/ClassicUT/1.gif" width=1 height=1></td>
	<td rowspan="2" colspan="2"><img vspace="0" hspace="0" src="/images/ClassicUT/5-2.gif" width=25 height=21 align="right"></td>
  </tr>
  <tr>
    <td width="100%" height="12" bgcolor="#135565"><img vspace="0" hspace="0" src="/images/ClassicUT/1.gif" width=1 height=1></td>
  </tr>
  <tr>
    <td width="9" bgcolor="#226474"><img vspace="0" hspace="0" src="/images/ClassicUT/1.gif" width=1 height=1></td>
	<td width="15" bgcolor="#135565"><img vspace="0" hspace="0" src="/images/ClassicUT/1.gif" width=1 height=1></td>
	<td width="100%" bgcolor="#135565"><font face="Verdana,Arial" color="White">
	<%Status%>
